package multichannel

import "time"

// Task represents a unit of work retrieved from a transport.
type Task struct {
	ID        string
	Payload   []byte
	Metadata  map[string]string
	CreatedAt time.Time
}

// Result represents output generated by a completed task.
type Result struct {
	TaskID     string
	Payload    []byte
	BlobRef    string
	Metadata   map[string]string
	FinishedAt time.Time
}

// BlobRef stores a pointer returned by upload-capable transports.
type BlobRef struct {
	Reference string
	Metadata  map[string]string
}

// TransportHealth represents a current transport status.
type TransportHealth string

const (
	HealthOK      TransportHealth = "ok"
	HealthDegraded TransportHealth = "degraded"
	HealthDown     TransportHealth = "down"
)

// Status is returned by transport health checks.
type Status struct {
	State   TransportHealth
	Message string
}
